volumes:
  foodgram_data:
  static_volume:
  media_volume:
  
services:
  foodgram_db:
    image: postgres:13
    env_file: ../backend/foodgram/.env
    volumes:
      - foodgram_data:/var/lib/postgresql/data/

  frontend:
    build: clinkyclink/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.25.4-alpine
    ports:
      - "7000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - backend
      - frontend

  backend:
    build: clinkyclink/foodgram_backend
    env_file: ../backend/foodgram/.env
    depends_on:
      - foodgram_db
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
